name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REPO_OS_OVERRIDE: linux
      ANDROID_HOME: ${{ github.workspace }}/.android-sdk
      ANDROID_NDK_HOME: ${{ github.workspace }}/.buildozer/android/platform/android-ndk-r21e
      ANDROID_NDK_ROOT: ${{ github.workspace }}/.buildozer/android/platform/android-ndk-r21e

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libssl-dev libffi-dev python3-dev \
                            libpython3-dev zlib1g-dev libncurses5-dev libgdbm-dev \
                            libnss3-dev libsqlite3-dev libreadline-dev libbz2-dev \
                            liblzma-dev tk-dev libxml2-dev libxmlsec1-dev libffi-dev \
                            liblzma-dev git zip unzip openjdk-8-jdk curl

    - name: Install pip dependencies
      run: |
        pip install --upgrade pip
        pip install setuptools wheel cython==0.29.33

    - name: Install Buildozer and requirements
      run: |
        pip install buildozer

    - name: Install Android SDK and accept licenses
      run: |
        mkdir -p $ANDROID_HOME/cmdline-tools
        cd $ANDROID_HOME/cmdline-tools
        curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        unzip sdk-tools.zip
        yes | $ANDROID_HOME/cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-30" "build-tools;30.0.3" --licenses
        yes | $ANDROID_HOME/cmdline-tools/cmdline-tools/bin/sdkmanager --update

    - name: Build the APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: MyApp.apk
        path: bin/*.apk